//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.OpenManipulator
{
    [Serializable]
    public class SetJointPositionResponse : Message
    {
        public const string k_RosMessageName = "open_manipulator_msgs/SetJointPosition";
        public override string RosMessageName => k_RosMessageName;

        public bool is_planned;

        public SetJointPositionResponse()
        {
            this.is_planned = false;
        }

        public SetJointPositionResponse(bool is_planned)
        {
            this.is_planned = is_planned;
        }

        public static SetJointPositionResponse Deserialize(MessageDeserializer deserializer) => new SetJointPositionResponse(deserializer);

        private SetJointPositionResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.is_planned);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.is_planned);
        }

        public override string ToString()
        {
            return "SetJointPositionResponse: " +
            "\nis_planned: " + is_planned.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
