//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.OpenManipulator
{
    [Serializable]
    public class SetJointPositionRequest : Message
    {
        public const string k_RosMessageName = "open_manipulator_msgs/SetJointPosition";
        public override string RosMessageName => k_RosMessageName;

        public string planning_group;
        public JointPositionMsg joint_position;
        public double path_time;

        public SetJointPositionRequest()
        {
            this.planning_group = "";
            this.joint_position = new JointPositionMsg();
            this.path_time = 0.0;
        }

        public SetJointPositionRequest(string planning_group, JointPositionMsg joint_position, double path_time)
        {
            this.planning_group = planning_group;
            this.joint_position = joint_position;
            this.path_time = path_time;
        }

        public static SetJointPositionRequest Deserialize(MessageDeserializer deserializer) => new SetJointPositionRequest(deserializer);

        private SetJointPositionRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.planning_group);
            this.joint_position = JointPositionMsg.Deserialize(deserializer);
            deserializer.Read(out this.path_time);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.planning_group);
            serializer.Write(this.joint_position);
            serializer.Write(this.path_time);
        }

        public override string ToString()
        {
            return "SetJointPositionRequest: " +
            "\nplanning_group: " + planning_group.ToString() +
            "\njoint_position: " + joint_position.ToString() +
            "\npath_time: " + path_time.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
